### PR TITLE
Connect backend and frontend

### PR DESCRIPTION
**Pull request by palak199**
The second PR, where we have connected the templates to backend

### CODE REVIEW

**Comment by SatinderpalSingh** [comment]
Resolve the conflict and then send the PR and also you have to send PR Head branch: projects to base branch: projects

**Comment by SatinderpalSingh** [comment]
Why you are modifying the files of team a1i3ns

**Comment by palak199** [comment]
> Why you are modifying the files of team a1i3ns

> Resolve the conflict and then send the PR and also you have to send PR Head branch: projects to base branch: projects

Sir I have resolved the conflict, and would send the next PR as told now

**Comment by SatinderpalSingh** [comment]
But why are you merging from your main to projects repo. It must be from projects repo from your side to projects repository of GNDEC

**Comment by palak199** [comment]
> But why are you merging from your main to projects repo. It must be from projects repo from your side to projects repository of GNDEC

Sir the PR was made earlier, need I close this and open another?

**Comment by SatinderpalSingh** [comment]
But It is still showing this to me: 

<q>palak199 wants to merge 55 commits into Computer-Science-and-Engineering-GNDEC:projects from she-coders:main</q>

**Comment by palak199** [comment]
> But It is still showing this to me:
> 
> palak199 wants to merge 55 commits into Computer-Science-and-Engineering-GNDEC:projects from she-coders:main

sir then should i close this and open another one ?

**Comment by SatinderpalSingh** [comment]
May be

**Pull request closed without merging**
