### PR TITLE
Created Dashboard

### PR DESCRIPTION
**Pull request by raghavbansal27**

### CODE REVIEW

**Comment by SatinderpalSingh** [comment]
Send the PR to projects branch instead of base branch

**Comment by raghavbansal27** [comment]
Sir, I sent PR to `Computer-Science-and-Engineering-GNDEC:projects` because it's showing "
raghavbansal27 wants to merge 4 commits into Computer-Science-and-Engineering-GNDEC:projects from su-assassins:main"

**Comment by SatinderpalSingh** [comment]
The must be  a projects branch in your repository also and it must be like
<q>
raghavbansal27 wants to merge 4 commits into Computer-Science-and-Engineering-GNDEC:projects from su-assassins:projects"
</q>

**Comment by raghavbansal27** [comment]
Okay, sir. I am closing this PR and creating a new one.

**Pull request closed without merging**
